source 'https://github.com/CocoaPods/Specs.git'

target 'Test Runner' do
  platform :ios, '8.0'
  use_frameworks!

  pod "SKYKit", :path => "../"
  pod "SKYKit/Facebook", :path => "../"
end

target 'Swift Example' do
  platform :ios, '8.0'
  use_frameworks!

  pod "SKYKit", :path => "../"
  pod "SKYKit/Facebook", :path => "../"
end

target 'Tests' do
  platform :ios, '8.0'
  use_frameworks!

  pod "SKYKit", :path => "../"
  pod "SKYKit/Facebook", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'OHHTTPStubs'
  pod 'OCMock'
end

target 'Mac Example' do
  platform :osx, '10.9'
  use_frameworks!

  pod "SKYKit/Core", :path => "../"
end

post_install do |installer|
  installer.aggregate_targets.each do |aggregate_target|
    if aggregate_target.name == "Pods-Tests"
      puts "Updating #{aggregate_target.name} HEADER_SEARCH_PATHS"
      aggregate_target.xcconfigs.each do |config_name, config_file|
        config_file.attributes['HEADER_SEARCH_PATHS'] << ' "${PODS_ROOT}/Headers/Private/SKYKit"'
        xcconfig_path = aggregate_target.xcconfig_path(config_name)
        config_file.save_as(xcconfig_path)
      end
    end
  end

  # Set "Treat Warnings as Errors" build settings.
  # Only warnings in the SKYKit targets will be treated as errors.
  # To disable, comment this section and run `pod install`.
  installer.pods_project.targets.each do |target|
    if target.name.start_with?("SKYKit")
      puts "Updating #{target.name} GCC_TREAT_WARNINGS_AS_ERRORS"
      target.build_configurations.each do |config|
        config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'YES'
      end
    end
  end
end
