source 'https://github.com/CocoaPods/Specs.git'

target 'SkyKit', :exclusive => true do
  pod "SkyKit", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "SkyKit", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'OHHTTPStubs'
  pod 'OCMock'
end
